export const cities: string[] = [
  // Megacidades e Polos Industriais (Alta densidade de poluentes)
  "Beijing",
  "Shanghai",
  "Guangzhou",
  "Tokyo",
  "Seoul",
  "Delhi",
  "Mumbai",
  "Kolkata",
  "Dhaka",
  "Karachi",
  "Cairo",
  "Lagos",
  "Kinshasa",
  "Mexico City",
  "Sao Paulo",
  "Jakarta",
  "Bangkok",
  "Manila",
  "Ho Chi Minh City",
  "Istanbul",
  "Moscow",
  "London",
  "Paris",
  "Berlin",
  "Madrid",
  "Rome",
  "New York",
  "Los Angeles",
  "Chicago",
  "Houston",
  "Toronto",
  "Sydney",

  // Cidades em Vales ou Bacias (Efeito de Inversão Térmica)
  "Santiago",
  "Medellin",
  "Salt Lake City",
  "Milan",
  "Kathmandu",
  "Tehran",
  "Almaty",
  "Ulaanbaatar",
  "Sarajevo",
  "Skopje",
  "Grenoble",
  "Stuttgart",

  // Fronteiras e Regiões Satélites
  "Singapore",
  "Kuala Lumpur",
  "Johannesburg",
  "Nairobi",
  "Addis Ababa",
  "Casablanca",
  "Riyadh",
  "Dubai",
  "Kuwait City",
  "Doha",
  "Tel Aviv",
  "Warsaw",
  "Kyiv",
  "Bucharest",
  "Athens",
  "Prague",
  "Vienna",
  "Brussels",
  "Amsterdam",
  "Stockholm",
  "Oslo",
  "Helsinki",
  "Copenhagen",
  "Dublin",
  "Lisbon",
  "Buenos Aires",
  "Lima",
  "Bogota",
  "Quito",
  "Caracas",

  // Focos de Atividade Específica (Petróleo/Indústria/Mineração)
  "Norilsk",
  "Oskemen",
  "Linfen",
  "Peshawar",
  "Lahore",
  "Baghdad",
  "Baku",
  "Perth",
  "Brisbane",
  "Vancouver",
  "Montreal",
  "Phoenix",
  "Denver",
  "Atlanta",
  "Miami",
  "Seattle",

  // Cidades de Controle (Baixa poluição/Ar limpo para comparação)
  "Reykjavik",
  "Wellington",
  "Zurich",
  "Calgary",
  "Hobart",
  "Honolulu",
  "Cape Town",
  "Edinburgh",
  "Berne",
  "Auckland",
].sort();
